# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
      - name: Test with ant
        run: |
          ant runtest -Dtest=TupleDescTest
          ant runtest -Dtest=TupleTest
          ant runtest -Dtest=CatalogTest
          ant runtest -Dtest=HeapPageIdTest
          ant runtest -Dtest=RecordIdTest
          ant runtest -Dtest=HeapPageReadTest
          ant runtest -Dtest=HeapFileReadTest
          ant runsystest -Dtest=ScanTest
          ant runtest -Dtest=PredicateTest
          ant runtest -Dtest=JoinPredicateTest
          ant runtest -Dtest=FilterTest
          ant runsystest -Dtest=FilterTest
          ant runtest -Dtest=JoinTest
          ant runsystest -Dtest=JoinTest
          ant runtest -Dtest=IntegerAggregatorTest
          ant runtest -Dtest=StringAggregatorTest
          ant runtest -Dtest=AggregateTest
          ant runsystest -Dtest=AggregateTest